name: 多看阅读

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,3,6 * * *'
  watch:
    types: [started]
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行【多看阅读】' 
        run: python3 main.py 
        env:
            COOKIES: ${{ secrets.COOKIES }}
            QYWX_AM: ${{ secrets.QYWX_AM }}
