name: enshan

on:
  workflow_dispatch:
  schedule:
    - cron: '5 17 * * *'
  watch:
    types: [started]
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行恩山签到' 
        run: python3 enshan.py 
        env:
            COOKIE_ENSHAN: ${{ secrets.COOKIE_ENSHAN }}
            QYWX_AM: ${{ secrets.QYWX_AM }}
